env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - standard
  - prettier
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 13
  sourceType: module
  project: ./tsconfig.json
plugins:
  - react
  - '@typescript-eslint'
rules: {
  "no-use-before-define": "off",
  "@typescript-eslint/no-use-before-define": ["error"],
}
settings:
  react:
    version: detect
